services:
  algasensors-rabbitmq:
    image: rabbitmq:3-management
    restart: no
    container_name: algasensors-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - algasensors-rabbitmq:/var/lib/rabbitmq
volumes:
    algasensors-rabbitmq: